//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.08 at 04:51:38 PM IST 
//


package com.rpa.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="loginUserRights" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element ref="{http://bdo.ws.jts.omni.newgen.com/NGOAddDocumentService/}NGOGetDocListDocDataBDO" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "loginUserRights",
    "message",
    "statusCode",
    "ngoGetDocListDocDataBDO"
})
@XmlRootElement(name = "NGOAddDocumentResponseBDO")
public class NGOAddDocumentResponseBDO {

    @XmlElement(required = true, nillable = true)
    protected String loginUserRights;
    @XmlElement(required = true, nillable = true)
    protected String message;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer statusCode;
    @XmlElement(name = "NGOGetDocListDocDataBDO", namespace = "http://bdo.ws.jts.omni.newgen.com/NGOAddDocumentService/", nillable = true)
    protected NGOGetDocListDocDataBDO ngoGetDocListDocDataBDO;

    /**
     * Gets the value of the loginUserRights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginUserRights() {
        return loginUserRights;
    }

    /**
     * Sets the value of the loginUserRights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginUserRights(String value) {
        this.loginUserRights = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStatusCode(Integer value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the ngoGetDocListDocDataBDO property.
     * 
     * @return
     *     possible object is
     *     {@link NGOGetDocListDocDataBDO }
     *     
     */
    public NGOGetDocListDocDataBDO getNGOGetDocListDocDataBDO() {
        return ngoGetDocListDocDataBDO;
    }

    /**
     * Sets the value of the ngoGetDocListDocDataBDO property.
     * 
     * @param value
     *     allowed object is
     *     {@link NGOGetDocListDocDataBDO }
     *     
     */
    public void setNGOGetDocListDocDataBDO(NGOGetDocListDocDataBDO value) {
        this.ngoGetDocListDocDataBDO = value;
    }

}
