//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.08 at 04:51:38 PM IST 
//


package com.rpa.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dataDefIndex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="dataDefName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element ref="{http://bdo.ws.jts.omni.newgen.com/NGOAddDocumentService/}NGOAddDocDataDefCriteriaDataBDO" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataDefIndex",
    "dataDefName",
    "ngoAddDocDataDefCriteriaDataBDO"
})
public class NGOAddDocDataDefCriterionBDO {

    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer dataDefIndex;
    @XmlElement(required = true, nillable = true)
    protected String dataDefName;
    @XmlElement(name = "NGOAddDocDataDefCriteriaDataBDO", namespace = "http://bdo.ws.jts.omni.newgen.com/NGOAddDocumentService/", required = true, nillable = true)
    protected List<NGOAddDocDataDefCriteriaDataBDO> ngoAddDocDataDefCriteriaDataBDO;

    /**
     * Gets the value of the dataDefIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDataDefIndex() {
        return dataDefIndex;
    }

    /**
     * Sets the value of the dataDefIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDataDefIndex(Integer value) {
        this.dataDefIndex = value;
    }

    /**
     * Gets the value of the dataDefName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataDefName() {
        return dataDefName;
    }

    /**
     * Sets the value of the dataDefName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataDefName(String value) {
        this.dataDefName = value;
    }

    /**
     * Gets the value of the ngoAddDocDataDefCriteriaDataBDO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ngoAddDocDataDefCriteriaDataBDO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNGOAddDocDataDefCriteriaDataBDO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NGOAddDocDataDefCriteriaDataBDO }
     * 
     * 
     */
    public List<NGOAddDocDataDefCriteriaDataBDO> getNGOAddDocDataDefCriteriaDataBDO() {
        if (ngoAddDocDataDefCriteriaDataBDO == null) {
            ngoAddDocDataDefCriteriaDataBDO = new ArrayList<NGOAddDocDataDefCriteriaDataBDO>();
        }
        return this.ngoAddDocDataDefCriteriaDataBDO;
    }

	/*public List<NGOAddDocDataDefCriteriaDataBDO> getNgoAddDocDataDefCriteriaDataBDO() {
		return ngoAddDocDataDefCriteriaDataBDO;
	}

	public void setNgoAddDocDataDefCriteriaDataBDO(List<NGOAddDocDataDefCriteriaDataBDO> ngoAddDocDataDefCriteriaDataBDO) {
		this.ngoAddDocDataDefCriteriaDataBDO = ngoAddDocDataDefCriteriaDataBDO;
	}*/

    
}
