//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.08 at 04:51:38 PM IST 
//


package com.rpa.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataDefIndex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="dataDefName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="enableLogFlag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="loginUserRights" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element ref="{http://bdo.ws.jts.omni.newgen.com/NGOAddDocumentService/}NGODataDefFieldBDO" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comment",
    "dataDefIndex",
    "dataDefName",
    "enableLogFlag",
    "groupId",
    "loginUserRights",
    "type",
    "ngoDataDefFieldBDO"
})
public class NGODataDefinitionBDO {

    @XmlElement(required = true, nillable = true)
    protected String comment;
    protected int dataDefIndex;
    @XmlElement(required = true)
    protected String dataDefName;
    @XmlElement(required = true, nillable = true)
    protected String enableLogFlag;
    @XmlElement(required = true, nillable = true)
    protected String groupId;
    @XmlElement(required = true, nillable = true)
    protected String loginUserRights;
    @XmlElement(required = true, nillable = true)
    protected String type;
    @XmlElement(name = "NGODataDefFieldBDO", namespace = "http://bdo.ws.jts.omni.newgen.com/NGOAddDocumentService/", required = true, nillable = true)
    protected List<NGODataDefFieldBDO> ngoDataDefFieldBDO;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the dataDefIndex property.
     * 
     */
    public int getDataDefIndex() {
        return dataDefIndex;
    }

    /**
     * Sets the value of the dataDefIndex property.
     * 
     */
    public void setDataDefIndex(int value) {
        this.dataDefIndex = value;
    }

    /**
     * Gets the value of the dataDefName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataDefName() {
        return dataDefName;
    }

    /**
     * Sets the value of the dataDefName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataDefName(String value) {
        this.dataDefName = value;
    }

    /**
     * Gets the value of the enableLogFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnableLogFlag() {
        return enableLogFlag;
    }

    /**
     * Sets the value of the enableLogFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnableLogFlag(String value) {
        this.enableLogFlag = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the loginUserRights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginUserRights() {
        return loginUserRights;
    }

    /**
     * Sets the value of the loginUserRights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginUserRights(String value) {
        this.loginUserRights = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the ngoDataDefFieldBDO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ngoDataDefFieldBDO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNGODataDefFieldBDO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NGODataDefFieldBDO }
     * 
     * 
     */
    public List<NGODataDefFieldBDO> getNGODataDefFieldBDO() {
        if (ngoDataDefFieldBDO == null) {
            ngoDataDefFieldBDO = new ArrayList<NGODataDefFieldBDO>();
        }
        return this.ngoDataDefFieldBDO;
    }

}
