//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.08 at 04:51:38 PM IST 
//


package com.rpa.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="indexAttribute" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="indexFlag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="indexId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="indexLength" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="indexName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="indexType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="indexValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="usefulInfoFlag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="usefulInfoSize" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "indexAttribute",
    "indexFlag",
    "indexId",
    "indexLength",
    "indexName",
    "indexType",
    "indexValue",
    "usefulInfoFlag",
    "usefulInfoSize"
})
public class NGODataDefFieldBDO {

    @XmlElement(required = true, nillable = true)
    protected String indexAttribute;
    @XmlElement(required = true, nillable = true)
    protected String indexFlag;
    @XmlElement(required = true, nillable = true)
    protected String indexId;
    @XmlElement(required = true, nillable = true)
    protected String indexLength;
    @XmlElement(required = true, nillable = true)
    protected String indexName;
    @XmlElement(required = true, nillable = true)
    protected String indexType;
    @XmlElement(required = true, nillable = true)
    protected String indexValue;
    @XmlElement(required = true, nillable = true)
    protected String usefulInfoFlag;
    @XmlElement(required = true, nillable = true)
    protected String usefulInfoSize;

    /**
     * Gets the value of the indexAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexAttribute() {
        return indexAttribute;
    }

    /**
     * Sets the value of the indexAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexAttribute(String value) {
        this.indexAttribute = value;
    }

    /**
     * Gets the value of the indexFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexFlag() {
        return indexFlag;
    }

    /**
     * Sets the value of the indexFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexFlag(String value) {
        this.indexFlag = value;
    }

    /**
     * Gets the value of the indexId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexId() {
        return indexId;
    }

    /**
     * Sets the value of the indexId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexId(String value) {
        this.indexId = value;
    }

    /**
     * Gets the value of the indexLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexLength() {
        return indexLength;
    }

    /**
     * Sets the value of the indexLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexLength(String value) {
        this.indexLength = value;
    }

    /**
     * Gets the value of the indexName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * Sets the value of the indexName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexName(String value) {
        this.indexName = value;
    }

    /**
     * Gets the value of the indexType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexType() {
        return indexType;
    }

    /**
     * Sets the value of the indexType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexType(String value) {
        this.indexType = value;
    }

    /**
     * Gets the value of the indexValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexValue() {
        return indexValue;
    }

    /**
     * Sets the value of the indexValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexValue(String value) {
        this.indexValue = value;
    }

    /**
     * Gets the value of the usefulInfoFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsefulInfoFlag() {
        return usefulInfoFlag;
    }

    /**
     * Sets the value of the usefulInfoFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsefulInfoFlag(String value) {
        this.usefulInfoFlag = value;
    }

    /**
     * Gets the value of the usefulInfoSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsefulInfoSize() {
        return usefulInfoSize;
    }

    /**
     * Sets the value of the usefulInfoSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsefulInfoSize(String value) {
        this.usefulInfoSize = value;
    }

}
