//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.08 at 04:51:38 PM IST 
//


package com.rpa.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="inputXML" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="base64Encoded" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputXML",
    "base64Encoded"
})
@XmlRootElement(name = "NGOExecuteAPIBDO", namespace = "http://bdo.ws.jts.omni.newgen.com/NGOExecuteAPIService/")
public class NGOExecuteAPIBDO {

    @XmlElement(required = true)
    protected String inputXML;
    @XmlElement(required = true, nillable = true)
    protected String base64Encoded;

    /**
     * Gets the value of the inputXML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputXML() {
        return inputXML;
    }

    /**
     * Sets the value of the inputXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputXML(String value) {
        this.inputXML = value;
    }

    /**
     * Gets the value of the base64Encoded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase64Encoded() {
        return base64Encoded;
    }

    /**
     * Sets the value of the base64Encoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase64Encoded(String value) {
        this.base64Encoded = value;
    }

}
